[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "stamp"
version = "1.0.3"
authors = [
  { name="Omar El Nahhas", email="omar.el_nahhas@tu-dresden.de" },
  { name="Marko van Treeck", email="markovantreeck@gmail.com" },
  { name="Georg Wölflein", email="georgw7777@gmail.com" },
  { name="Tim Lenz", email="tim.lenz@tu-dresden.de" },
  { name="Laura Žigutytė", email="laura.zigutyte@tu-dresden.de" },
  { name="Cornelius Kummer", email="cornelius.kummer@tu-dresden.de" },
]
description = "A protocol for Solid Tumor Associative Modeling in Pathology"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "pandas~=2.1",
  "matplotlib~=3.8",
  "scikit-learn~=1.3",
  "tqdm~=4.66",
  "fastai~=2.7",
  "torch~=2.0",
  "torchvision~=0.15",
  "h5py~=3.10",
  "jaxtyping~=0.2",
  "einops~=0.7",
  "omegaconf~=2.3",
  "openslide-python~=1.3",
  "opencv-python~=4.8",
  "numba~=0.58",
  "gdown~=4.7",
  "openpyxl~=3.1",
  "UNI@git+https://github.com/mahmoodlab/UNI.git"
]

[project.scripts]
"stamp" = "stamp.cli:main"

[project.urls]
"Homepage" = "https://github.com/Avic3nna/STAMP"
"Bug Tracker" = "https://github.com/Avic3nna/STAMP/issues"

[tool.hatch.build]
include = [
  "stamp/**/*"
]